#!/bin/bash

for i in $(cat /home/conrad/Data/160902_NextSeq/file_index)

do

  /home/conrad/Software/bcftools-1.3.1/bcftools call -c -v --ploidy 1 /home/conrad/Data/160902_NextSeq/Trevors_strains/wspF_cdrA_ref_alignment/Alignments/genotype_likelihood_files/bcf_files/$i"_PAO1_aln.bcf" > /home/conrad/Data/160902_NextSeq/Trevors_strains/wspF_cdrA_ref_alignment/Alignments/genotype_likelihood_files/vcf_files/$i"_PAO1_aln.vcf"

done
