#!/bin/bash

echo 'Now working on isolate '6
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/6_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/6_R2.fastq -i PE 366,158 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/6_aln.sam
echo 'Now working on isolate '7
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/7_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/7_R2.fastq -i PE 476,171 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/7_aln.sam
echo 'Now working on isolate '8
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/8_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/8_R2.fastq -i PE 395,171 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/8_aln.sam
echo 'Now working on isolate '10
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/10_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/10_R2.fastq -i PE 370,165 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/10_aln.sam
echo 'Now working on isolate '14
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/14_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/14_R2.fastq -i PE 387,170 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/14_aln.sam
echo 'Now working on isolate '17
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/17_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/17_R2.fastq -i PE 396,178 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/17_aln.sam
echo 'Now working on isolate '152
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/152_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/152_R2.fastq -i PE 404,167 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/152_aln.sam
echo 'Now working on isolate '160
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/160_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/160_R2.fastq -i PE 423,181 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/160_aln.sam
echo 'Now working on isolate '180
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/180_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/180_R2.fastq -i PE 417,179 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/180_aln.sam
echo 'Now working on isolate '196
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/196_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/196_R2.fastq -i PE 431,173 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/196_aln.sam
echo 'Now working on isolate '200
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/200_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/200_R2.fastq -i PE 402,173 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/200_aln.sam
echo 'Now working on isolate '217
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/217_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/217_R2.fastq -i PE 427,167 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/217_aln.sam
echo 'Now working on isolate '225
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/225_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/225_R2.fastq -i PE 425,172 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/225_aln.sam
echo 'Now working on isolate '235
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/235_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/235_R2.fastq -i PE 419,167 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/235_aln.sam
echo 'Now working on isolate '251
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/251_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/251_R2.fastq -i PE 401,165 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/251_aln.sam
echo 'Now working on isolate '257
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/257_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/257_R2.fastq -i PE 399,166 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/257_aln.sam
echo 'Now working on isolate '258
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/258_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/258_R2.fastq -i PE 388,161 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/258_aln.sam
echo 'Now working on isolate '259
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/259_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/259_R2.fastq -i PE 406,169 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/259_aln.sam
echo 'Now working on isolate '265
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/265_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/265_R2.fastq -i PE 422,169 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/265_aln.sam
echo 'Now working on isolate '270
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/270_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/270_R2.fastq -i PE 403,166 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/270_aln.sam
echo 'Now working on isolate '273
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/273_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/273_R2.fastq -i PE 419,177 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/273_aln.sam
echo 'Now working on isolate '276
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/276_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/276_R2.fastq -i PE 434,185 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/276_aln.sam
echo 'Now working on isolate '282
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/282_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/282_R2.fastq -i PE 422,188 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/282_aln.sam
echo 'Now working on isolate '275
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/275_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/275_R2.fastq -i PE 422,183 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/275_aln.sam
echo 'Now working on isolate '278
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/278_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/278_R2.fastq -i PE 420,176 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/278_aln.sam
echo 'Now working on isolate '280
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/280_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/280_R2.fastq -i PE 418,171 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/280_aln.sam
echo 'Now working on isolate '288
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/288_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/288_R2.fastq -i PE 413,178 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/288_aln.sam
echo 'Now working on isolate '290
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/290_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/290_R2.fastq -i PE 412,165 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/290_aln.sam
echo 'Now working on isolate '293
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/293_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/293_R2.fastq -i PE 424,190 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/293_aln.sam
echo 'Now working on isolate '298
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/298_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/298_R2.fastq -i PE 443,183 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/298_aln.sam
echo 'Now working on isolate '303
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/303_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/303_R2.fastq -i PE 416,157 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/303_aln.sam
echo 'Now working on isolate '304
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/304_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/304_R2.fastq -i PE 415,166 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/304_aln.sam
echo 'Now working on isolate '306
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/306_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/306_R2.fastq -i PE 390,163 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/306_aln.sam
echo 'Now working on isolate '310
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/310_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/310_R2.fastq -i PE 405,156 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/310_aln.sam
echo 'Now working on isolate '315
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/315_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/315_R2.fastq -i PE 416,174 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/315_aln.sam
echo 'Now working on isolate '317
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/317_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/317_R2.fastq -i PE 412,172 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/317_aln.sam
echo 'Now working on isolate '318
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/318_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/318_R2.fastq -i PE 424,177 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/318_aln.sam
echo 'Now working on isolate '323
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/323_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/323_R2.fastq -i PE 412,173 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/323_aln.sam
echo 'Now working on isolate '325
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/325_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/325_R2.fastq -i PE 431,173 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/325_aln.sam
echo 'Now working on isolate '326
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/326_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/326_R2.fastq -i PE 412,175 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/326_aln.sam
echo 'Now working on isolate '327
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/327_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/327_R2.fastq -i PE 405,180 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/327_aln.sam
echo 'Now working on isolate '330
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/330_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/330_R2.fastq -i PE 419,176 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/330_aln.sam
echo 'Now working on isolate '331
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/331_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/331_R2.fastq -i PE 403,168 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/331_aln.sam
echo 'Now working on isolate '332
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/332_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/332_R2.fastq -i PE 423,172 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/332_aln.sam
echo 'Now working on isolate '335
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/335_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/335_R2.fastq -i PE 410,171 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/335_aln.sam
echo 'Now working on isolate '336
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/336_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/336_R2.fastq -i PE 477,176 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/336_aln.sam
echo 'Now working on isolate '337
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/337_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/337_R2.fastq -i PE 430,178 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/337_aln.sam
echo 'Now working on isolate '340
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/340_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/340_R2.fastq -i PE 379,147 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/340_aln.sam
echo 'Now working on isolate '341
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/341_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/341_R2.fastq -i PE 438,181 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/341_aln.sam
echo 'Now working on isolate '342
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/342_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/342_R2.fastq -i PE 533,182 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/342_aln.sam
echo 'Now working on isolate '358
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/358_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/358_R2.fastq -i PE 422,171 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/358_aln.sam
echo 'Now working on isolate '359
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/359_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/359_R2.fastq -i PE 411,175 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/359_aln.sam
echo 'Now working on isolate '360
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/360_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/360_R2.fastq -i PE 497,170 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/360_aln.sam
echo 'Now working on isolate '366
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/366_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/366_R2.fastq -i PE 404,175 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/366_aln.sam
echo 'Now working on isolate '367
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/367_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/367_R2.fastq -i PE 429,177 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/367_aln.sam
echo 'Now working on isolate '369
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/369_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/369_R2.fastq -i PE 428,175 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/369_aln.sam
echo 'Now working on isolate '375
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/375_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/375_R2.fastq -i PE 371,155 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/375_aln.sam
echo 'Now working on isolate '379
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/379_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/379_R2.fastq -i PE 424,164 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/379_aln.sam
echo 'Now working on isolate '380
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/380_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/380_R2.fastq -i PE 415,181 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/380_aln.sam
echo 'Now working on isolate '392
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/392_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/392_R2.fastq -i PE 454,176 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/392_aln.sam
echo 'Now working on isolate '401
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/401_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/401_R2.fastq -i PE 450,200 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/401_aln.sam
echo 'Now working on isolate '404
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/404_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/404_R2.fastq -i PE 464,195 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/404_aln.sam
echo 'Now working on isolate '405
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/405_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/405_R2.fastq -i PE 475,198 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/405_aln.sam
echo 'Now working on isolate '406
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/406_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/406_R2.fastq -i PE 406,173 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/406_aln.sam
echo 'Now working on isolate '409
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/409_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/409_R2.fastq -i PE 455,178 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/409_aln.sam
echo 'Now working on isolate '410
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/410_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/410_R2.fastq -i PE 440,181 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/410_aln.sam
echo 'Now working on isolate '411
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/411_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/411_R2.fastq -i PE 434,160 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/411_aln.sam
echo 'Now working on isolate '412
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/412_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/412_R2.fastq -i PE 408,154 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/412_aln.sam
echo 'Now working on isolate '417
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/417_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/417_R2.fastq -i PE 468,208 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/417_aln.sam
echo 'Now working on isolate '418
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/418_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/418_R2.fastq -i PE 459,196 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/418_aln.sam
echo 'Now working on isolate '419
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/419_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/419_R2.fastq -i PE 452,198 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/419_aln.sam
echo 'Now working on isolate '420
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/420_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/420_R2.fastq -i PE 425,171 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/420_aln.sam
echo 'Now working on isolate '430
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/430_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/430_R2.fastq -i PE 451,180 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/430_aln.sam
echo 'Now working on isolate '433
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/433_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/433_R2.fastq -i PE 434,178 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/433_aln.sam
echo 'Now working on isolate '446
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/446_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/446_R2.fastq -i PE 413,166 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/446_aln.sam
echo 'Now working on isolate '449
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/449_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/449_R2.fastq -i PE 416,166 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/449_aln.sam
echo 'Now working on isolate '450
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/450_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/450_R2.fastq -i PE 423,181 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/450_aln.sam
echo 'Now working on isolate '453
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/453_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/453_R2.fastq -i PE 416,174 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/453_aln.sam
echo 'Now working on isolate '455
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/455_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/455_R2.fastq -i PE 430,180 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/455_aln.sam
echo 'Now working on isolate '459
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/459_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/459_R2.fastq -i PE 436,181 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/459_aln.sam
echo 'Now working on isolate '472
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/472_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/472_R2.fastq -i PE 382,172 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/472_aln.sam
echo 'Now working on isolate '473
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/473_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/473_R2.fastq -i PE 398,170 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/473_aln.sam
echo 'Now working on isolate '475
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/475_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/475_R2.fastq -i PE 402,175 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/475_aln.sam
echo 'Now working on isolate '476
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/476_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/476_R2.fastq -i PE 394,172 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/476_aln.sam
echo 'Now working on isolate '479
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/479_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/479_R2.fastq -i PE 423,166 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/479_aln.sam
echo 'Now working on isolate '480
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/480_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/480_R2.fastq -i PE 402,177 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/480_aln.sam
echo 'Now working on isolate '503
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/503_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/503_R2.fastq -i PE 415,163 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/503_aln.sam
echo 'Now working on isolate '504
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/504_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/504_R2.fastq -i PE 423,176 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/504_aln.sam
echo 'Now working on isolate '505
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/505_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/505_R2.fastq -i PE 401,174 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/505_aln.sam
echo 'Now working on isolate '506
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/506_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/506_R2.fastq -i PE 411,163 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/506_aln.sam
echo 'Now working on isolate '507
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/507_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/507_R2.fastq -i PE 428,189 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/507_aln.sam
echo 'Now working on isolate '508
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/508_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/508_R2.fastq -i PE 387,172 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/508_aln.sam
echo 'Now working on isolate '509
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/509_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/509_R2.fastq -i PE 379,167 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/509_aln.sam
echo 'Now working on isolate '510
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/510_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/510_R2.fastq -i PE 386,171 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/510_aln.sam
echo 'Now working on isolate '511
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/511_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/511_R2.fastq -i PE 442,158 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/511_aln.sam
echo 'Now working on isolate '512
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/512_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/512_R2.fastq -i PE 446,163 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/512_aln.sam
echo 'Now working on isolate '513
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/513_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/513_R2.fastq -i PE 451,156 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/513_aln.sam
echo 'Now working on isolate '514
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/514_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/514_R2.fastq -i PE 445,153 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/514_aln.sam
echo 'Now working on isolate '521
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/521_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/521_R2.fastq -i PE 428,157 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/521_aln.sam
echo 'Now working on isolate '525
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/525_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/525_R2.fastq -i PE 434,181 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/525_aln.sam
echo 'Now working on isolate '526
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/526_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/526_R2.fastq -i PE 456,172 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/526_aln.sam
echo 'Now working on isolate '527
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/527_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/527_R2.fastq -i PE 423,176 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/527_aln.sam
echo 'Now working on isolate '528
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/528_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/528_R2.fastq -i PE 436,176 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/528_aln.sam
echo 'Now working on isolate '529
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/529_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/529_R2.fastq -i PE 469,154 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/529_aln.sam
echo 'Now working on isolate '530
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/530_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/530_R2.fastq -i PE 440,169 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/530_aln.sam
echo 'Now working on isolate '531
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/531_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/531_R2.fastq -i PE 472,178 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/531_aln.sam
echo 'Now working on isolate '532
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/532_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/532_R2.fastq -i PE 467,159 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/532_aln.sam
echo 'Now working on isolate '548
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/548_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/548_R2.fastq -i PE 434,185 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/548_aln.sam
echo 'Now working on isolate '550
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/550_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/550_R2.fastq -i PE 463,180 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/550_aln.sam
echo 'Now working on isolate '538
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/538_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/538_R2.fastq -i PE 484,170 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/538_aln.sam
echo 'Now working on isolate '539
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/539_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/539_R2.fastq -i PE 475,184 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/539_aln.sam
echo 'Now working on isolate '540
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/540_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/540_R2.fastq -i PE 446,176 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/540_aln.sam
echo 'Now working on isolate '541
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/541_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/541_R2.fastq -i PE 419,165 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/541_aln.sam
echo 'Now working on isolate '542
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/542_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/542_R2.fastq -i PE 473,174 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/542_aln.sam
echo 'Now working on isolate '544
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/544_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/544_R2.fastq -i PE 435,178 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/544_aln.sam
echo 'Now working on isolate '552
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/552_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/552_R2.fastq -i PE 422,184 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/552_aln.sam
echo 'Now working on isolate '553
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/553_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/553_R2.fastq -i PE 443,185 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/553_aln.sam
echo 'Now working on isolate '556
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/556_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/556_R2.fastq -i PE 431,192 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/556_aln.sam
echo 'Now working on isolate '557
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/557_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/557_R2.fastq -i PE 400,173 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/557_aln.sam
echo 'Now working on isolate '559
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/559_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/559_R2.fastq -i PE 408,161 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/559_aln.sam
echo 'Now working on isolate '562
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/562_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/562_R2.fastq -i PE 412,165 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/562_aln.sam
echo 'Now working on isolate '563
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/563_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/563_R2.fastq -i PE 423,185 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/563_aln.sam
echo 'Now working on isolate '566
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/566_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/566_R2.fastq -i PE 434,176 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/566_aln.sam
echo 'Now working on isolate '567
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/567_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/567_R2.fastq -i PE 421,179 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/567_aln.sam
echo 'Now working on isolate '568
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/568_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/568_R2.fastq -i PE 421,177 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/568_aln.sam
echo 'Now working on isolate '569
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/569_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/569_R2.fastq -i PE 476,168 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/569_aln.sam
echo 'Now working on isolate '570
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/570_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/570_R2.fastq -i PE 534,175 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/570_aln.sam
echo 'Now working on isolate '571
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/571_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/571_R2.fastq -i PE 432,179 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/571_aln.sam
echo 'Now working on isolate '572-1
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/572-1_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/572-1_R2.fastq -i PE 413,170 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/572-1_aln.sam
echo 'Now working on isolate '573-2
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/573-2_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/573-2_R2.fastq -i PE 372,155 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/573-2_aln.sam
echo 'Now working on isolate '573-3
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/573-3_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/573-3_R2.fastq -i PE 386,160 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/573-3_aln.sam
echo 'Now working on isolate '575
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/575_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/575_R2.fastq -i PE 396,161 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/575_aln.sam
echo 'Now working on isolate '577
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/577_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/577_R2.fastq -i PE 444,187 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/577_aln.sam
echo 'Now working on isolate '578
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/578_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/578_R2.fastq -i PE 440,162 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/578_aln.sam
echo 'Now working on isolate '579
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/579_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/579_R2.fastq -i PE 402,177 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/579_aln.sam
echo 'Now working on isolate '580
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/580_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/580_R2.fastq -i PE 435,175 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/580_aln.sam
echo 'Now working on isolate '581
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/581_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/581_R2.fastq -i PE 405,179 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/581_aln.sam
echo 'Now working on isolate '583
~/Software/novocraft/novoalign -d ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/PAO1_reference_genome/pao1reference -f ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/583_R1.fastq ~/Data/primary_project_2/fastq_files/good_fastq_files_E8/583_R2.fastq -i PE 430,173 -o SAM > ~/Data/primary_project_2/reference_alignments/F2_novoalign_alignment/sam_files/583_aln.sam
