#!/bin/bash

for i in $(cat /home/conrad/Data/160902_NextSeq/file_index)

do

  /home/conrad/Software/samtools-1.3.1/samtools sort -o /home/conrad/Data/160902_NextSeq/Trevors_strains/wspF_cdrA_ref_alignment/Alignments/samtools_bam_files/Sorted/$i"_PAO1_aln.sorted.bam" /home/conrad/Data/160902_NextSeq/Trevors_strains/wspF_cdrA_ref_alignment/Alignments/samtools_bam_files/Unsorted/$i"_PAO1_aln.bam"

done
